"""empty message

Revision ID: 05c8bdcf51e6
Revises: b50f0cbaf3a0
Create Date: 2020-02-06 13:23:13.886713

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '05c8bdcf51e6'
down_revision = 'b50f0cbaf3a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_genres', sa.Column('genre_name', sa.String(), nullable=True))
    op.add_column('artist_genres', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('artist_genres_genre_id_fkey', 'artist_genres', type_='foreignkey')
    op.drop_column('artist_genres', 'genre_id')
    op.add_column('venue_genres', sa.Column('genre_name', sa.String(), nullable=True))
    op.add_column('venue_genres', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('venue_genres', sa.Column('vanue_id', sa.Integer(), nullable=False))
    op.drop_constraint('venue_genres_genre_id_fkey', 'venue_genres', type_='foreignkey')
    op.drop_constraint('venue_genres_venue_id_fkey', 'venue_genres', type_='foreignkey')
    op.create_foreign_key(None, 'venue_genres', 'venues', ['vanue_id'], ['id'])
    op.drop_column('venue_genres', 'genre_id')
    op.drop_column('venue_genres', 'venue_id')
    op.drop_table('genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue_genres',
                  sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('venue_genres',
                  sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'venue_genres', type_='foreignkey')
    op.create_foreign_key('venue_genres_venue_id_fkey', 'venue_genres', 'venues', ['venue_id'],
                          ['id'])
    op.create_foreign_key('venue_genres_genre_id_fkey', 'venue_genres', 'genres', ['genre_id'],
                          ['id'])
    op.drop_column('venue_genres', 'vanue_id')
    op.drop_column('venue_genres', 'id')
    op.drop_column('venue_genres', 'genre_name')
    op.add_column('artist_genres',
                  sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('artist_genres_genre_id_fkey', 'artist_genres', 'genres', ['genre_id'],
                          ['id'])
    op.drop_column('artist_genres', 'id')
    op.drop_column('artist_genres', 'genre_name')
    op.create_table('genres', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='genres_pkey'))
    # ### end Alembic commands ###
