"""Something went wrong, drop all the tables to recreate one ones.

Revision ID: 0dba7b0a5c7d
Revises: 05c8bdcf51e6
Create Date: 2020-02-07 11:54:19.267945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0dba7b0a5c7d'
down_revision = '05c8bdcf51e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shows_venue_id_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('venue_genres_vanue_id_fkey', 'venue_genres', type_='foreignkey')
    op.drop_table('venues')
    op.drop_table('artist_genres')
    op.drop_table('shows')
    op.drop_table('venue_genres')
    op.drop_table('artists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
                    sa.Column('id',
                              sa.INTEGER(),
                              server_default=sa.text("nextval('artists_id_seq'::regclass)"),
                              autoincrement=True,
                              nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
                    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
                    sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
                    sa.Column('image_link',
                              sa.VARCHAR(length=500),
                              autoincrement=False,
                              nullable=True),
                    sa.Column('facebook_link',
                              sa.VARCHAR(length=120),
                              autoincrement=False,
                              nullable=True),
                    sa.Column('seeking_description',
                              sa.VARCHAR(),
                              autoincrement=False,
                              nullable=True),
                    sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('website', sa.VARCHAR(length=120), autoincrement=False,
                              nullable=True),
                    sa.PrimaryKeyConstraint('id', name='artists_pkey'),
                    postgresql_ignore_search_path=False)
    op.create_table(
        'venue_genres', sa.Column('genre_name', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('vanue_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['vanue_id'], ['venues.id'], name='venue_genres_vanue_id_fkey'))
    op.create_table(
        'shows', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name='shows_artist_id_fkey'),
        sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name='shows_venue_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='shows_pkey'))
    op.create_table(
        'artist_genres', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('genre_name', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name='artist_genres_artist_id_fkey'))
    op.create_table(
        'venues', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
        sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
        sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
        sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
        sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
        sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
        sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column('seeking_description', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='venues_pkey'))
    # ### end Alembic commands ###
