"""Create tables

Revision ID: 1973cab5f729
Revises: 0dba7b0a5c7d
Create Date: 2020-02-07 11:57:01.452005

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1973cab5f729'
down_revision = '0dba7b0a5c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('city', sa.String(length=120), nullable=True),
                    sa.Column('state', sa.String(length=120), nullable=True),
                    sa.Column('phone', sa.String(length=120), nullable=True),
                    sa.Column('image_link', sa.String(length=500), nullable=True),
                    sa.Column('facebook_link', sa.String(length=120), nullable=True),
                    sa.Column('website', sa.String(length=120), nullable=True),
                    sa.Column('seeking_venue', sa.Boolean(), nullable=True),
                    sa.Column('seeking_description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('venues', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('city', sa.String(length=120), nullable=True),
                    sa.Column('state', sa.String(length=120), nullable=True),
                    sa.Column('address', sa.String(length=120), nullable=True),
                    sa.Column('phone', sa.String(length=120), nullable=True),
                    sa.Column('image_link', sa.String(length=500), nullable=True),
                    sa.Column('facebook_link', sa.String(length=120), nullable=True),
                    sa.Column('website', sa.String(length=120), nullable=True),
                    sa.Column('seeking_talent', sa.Boolean(), nullable=True),
                    sa.Column('seeking_description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('artist_genres', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('genre_name', sa.String(), nullable=True),
                    sa.Column('artist_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['artist_id'],
                        ['artists.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    op.create_table('shows', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('start_time', sa.DateTime(), nullable=True),
                    sa.Column('venue_id', sa.Integer(), nullable=False),
                    sa.Column('artist_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['artist_id'],
                        ['artists.id'],
                    ), sa.ForeignKeyConstraint(
                        ['venue_id'],
                        ['venues.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    op.create_table('venue_genres', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('genre_name', sa.String(), nullable=True),
                    sa.Column('vanue_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['vanue_id'],
                        ['venues.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_genres')
    op.drop_table('shows')
    op.drop_table('artist_genres')
    op.drop_table('venues')
    op.drop_table('artists')
    # ### end Alembic commands ###
