"""empty message

Revision ID: 5f263d2aea7e
Revises: d83547a88f96
Create Date: 2020-02-11 14:05:46.610984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f263d2aea7e'
down_revision = 'd83547a88f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_available_times', sa.Column('time_from', sa.Time(), nullable=False))
    op.add_column('artist_available_times', sa.Column('time_to', sa.Time(), nullable=False))
    op.drop_column('artist_available_times', 'available_time_from')
    op.drop_column('artist_available_times', 'available_time_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_available_times', sa.Column('available_time_to', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('artist_available_times', sa.Column('available_time_from', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('artist_available_times', 'time_to')
    op.drop_column('artist_available_times', 'time_from')
    # ### end Alembic commands ###
