"""empty message

Revision ID: b6939551d29c
Revises: d32508e5f034
Create Date: 2020-02-10 16:21:07.789687

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b6939551d29c'
down_revision = 'd32508e5f034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue_genres', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.execute('UPDATE venue_genres set venue_id = vanue_id WHERE venue_id IS NULL;')
    op.alter_column('venue_genres', 'venue_id', nullable=False)
    op.drop_constraint('venue_genres_vanue_id_fkey', 'venue_genres', type_='foreignkey')
    op.create_foreign_key(None, 'venue_genres', 'venues', ['venue_id'], ['id'])
    op.drop_column('venue_genres', 'vanue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue_genres',
                  sa.Column('vanue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'venue_genres', type_='foreignkey')
    op.create_foreign_key('venue_genres_vanue_id_fkey', 'venue_genres', 'venues', ['vanue_id'],
                          ['id'])
    op.drop_column('venue_genres', 'venue_id')
    # ### end Alembic commands ###
